const container = document.getElementById('messages');

if (container) {
    container.scrollTop = container.scrollHeight;
}

if (window.conversationId) {
    Echo.private(`conversation.${window.conversationId}`)
        .listen('MessageSent', (data) => {
            if (data.sender_id !== window.currentUserId) {
                appendMessage(data.sender_name, data.body, false, data.created_at);
                
                // Update sidebar preview and move to top when receiving
                updateSidebar(data.conversation_id, data.body);
            }
        });
}

const input = document.getElementById('message-input');
const sendBtn = document.getElementById('send-btn');

if (input) {
    input.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') sendMessage();
    });
    sendBtn.addEventListener('click', sendMessage);
}

async function sendMessage() {
    const body = input.value.trim();
    if (!body) return;

    input.value = '';
    sendBtn.disabled = true;

    const id = window.conversationId || 0;

    try {
        const res = await fetch(`/chat/${id}/message`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
            },
            body: JSON.stringify({ 
                body: body,
                employer_id: window.targetEmployerId 
            }),
        });

        const data = await res.json();

        if (!window.conversationId && data.conversation_id) {
            window.conversationId = data.conversation_id;
            window.history.pushState({}, '', `/chat/${data.conversation_id}`);
            
            // Refresh on first message so the sidebar row is generated by PHP
            location.reload(); 
            return;
        }

        appendMessage('You', data.body, true, data.time);

        // Reorder sidebar items within the list wrapper
        updateSidebar(window.conversationId, data.body);

    } catch (e) {
        console.error("Failed to send message:", e);
    } finally {
        sendBtn.disabled = false;
    }
}

// Helper function to move chat to top of the list (below the header)
function updateSidebar(convId, lastBody) {
    const list = document.getElementById('conversation-list');
    const activeItem = document.querySelector(`.conversation-item[href*="/chat/${convId}"]`);
    
    if (activeItem && list) {
        // Update the preview text
        const preview = activeItem.querySelector('.conv-preview');
        if (preview) {
            preview.innerText = lastBody;
        }
        // Move to the very top of the #conversation-list div
        list.prepend(activeItem);
    }
}

function appendMessage(senderName, body, isMe, time) {
    let displayTime = time || new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    if (time && typeof time === 'string' && time.includes('T')) { 
        displayTime = new Date(time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    }

    const wrapper = document.createElement('div');
    wrapper.className = 'message-wrapper ' + (isMe ? 'sent' : 'received');
    
    wrapper.innerHTML = `
        ${!isMe ? `<div class="sender-name">${senderName}</div>` : ''}
        <div class="bubble">${body}</div>
        <div class="message-meta">${displayTime}</div>
    `;

    container.appendChild(wrapper);
    container.scrollTop = container.scrollHeight;
}